"""Start app

Revision ID: c5031e48a043
Revises: 8f8b629335c0
Create Date: 2022-08-04 19:34:31.846735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5031e48a043'
down_revision = '8f8b629335c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('create_date', sa.String(length=255), nullable=True))
    op.alter_column('attendance', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('attendance', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('attendance', 'datetime')
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('attendance', sa.Column('datetime', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('attendance', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('attendance', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('attendance', 'create_date')
    # ### end Alembic commands ###
